### ISSUE TITLE
Working tests have been commented out as a "fix"

### ISSUE THREAD

**Issue by jzahedieh** [ebizmarts/magento2-magemonkey#21]
### Situation - How did you get there?

Working tests have been commented out as a "fix"

    commit 223e663b1aceafa92daaa884d2e376d79a347d34
    Author: gonzalo <gonzalo@ebizmarts.com>
    Date:   Wed Apr 20 10:47:13 2016 -0300
    
        fix test

### Problem - What went wrong?

The tests have been updated for reasons I don't know but it seems like either the work was incomplete so the `testGetMergeVars` test was completely commented out and the `testGetDefaultList` test was updated and commented out.

### Possible solution - How should it be?

Revert the tests to the previous state and apply the update in a cleaner manner with some description on why the change was made.

**Comment by Santiagoebizmarts** [comment]
Hello @jzahedieh 
To be honest we are not dedicating much time to MageMonkey 2 because we are working on a new extension MailChimp For Magento which will replace MageMonkey when it becomes available.

We are doing bug fixes so if you have any problem with the extension don't hesitate to ask for help in our [forum](http://ebizmarts.com/forums/view/1) or create an issue here.

Thanks for your help and stay tuned for the new extension. We are really exited about it since it will allow the use of [MailChimp Automations](https://mailchimp.com/features/automation/) in addition to the usual Subscriber sync.

Regards.
