### ISSUE TITLE
Ebizmarts\MageMonkey\Model\Resource\Setup references class \Magento\Framework\Module\Updater\SetupInterface which no longer exists

### ISSUE THREAD

**Issue by andrewkett** [ebizmarts/magento2-magemonkey#4]
Ebizmarts\MageMonkey\Model\Resource\Setup references class \Magento\Framework\Module\Updater\SetupInterface which no longer exists. This is breaking bin/magento setup:di:compile

**Comment by zephir1** [comment]
Hi! I also found the error generating the setup:di:compile

I tried modifying the file app/code/Ebizmarts/MageMonkey/Model/Resource/Setup.php on line 15, 27 and 29 in order to extend the correct class. But a new error appears:
`Total Errors Count: 1
Errors during compilation:
        Ebizmarts\MageMonkey\Helper\Data
                Incorrect dependency in class Ebizmarts\MageMonkey\Helper\Data in /usr/share/nginx/www/magento/app/code/Ebizmarts/MageMonkey/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1`

**Comment by gonzaloebiz** [comment]
This is already fixed
